/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 健康检查
         * @description 进程级探活。**不访问数据库**，因此数据库挂掉时本接口仍返回 200。
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/observability/smoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 观测自检：一次被完整 trace 的 LLM 调用
         * @description 发起一次 LLM 调用并按 trace → generation 两级结构上报 Langfuse。
         *
         *     **失败也算通过**：调用异常时 trace 照常落库，只是 observation 标记为 ERROR —— 观测的价值恰恰在于失败可查。
         */
        post: operations["observability_smoke_api_v1_observability_smoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/observability/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 观测配置现状
         * @description 回答「trace 为什么没出现」：key 是否配齐、实例是否可达、LLM 是不是 stub。
         */
        get: operations["observability_status_api_v1_observability_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 系统信息
         * @description 穿透到 Postgres 的读库校验。数据库不可用时降级返回，接口本身不报错。
         */
        get: operations["system_info_api_v1_system_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 健康检查
         * @description 进程级探活。**不访问数据库**，因此数据库挂掉时本接口仍返回 200。
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * DatabaseStatus
         * @description 数据库探活结果。连不上不算接口失败，只降级。
         */
        DatabaseStatus: {
            /** Connected */
            connected: boolean;
            /**
             * Error
             * @description 连接失败原因，成功时为 null
             */
            error?: string | null;
            /**
             * Latency Ms
             * @description 探活往返耗时
             */
            latency_ms?: number | null;
            /**
             * Server Version
             * @description Postgres 版本
             */
            server_version?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description 进程级健康检查结果。不依赖数据库，永远能返回。
         * @example {
         *       "checked_at": "2026-10-08T12:00:00Z",
         *       "environment": "local",
         *       "service": "resume-optimizer-api",
         *       "status": "ok",
         *       "trace_id": "8f1c0b2e6a4d4a1f9c3e7b5d2a0f6c11",
         *       "uptime_seconds": 12.5,
         *       "version": "0.1.0"
         *     }
         */
        HealthResponse: {
            /**
             * Checked At
             * Format: date-time
             * @description 本次检查时间（UTC）
             */
            checked_at: string;
            /**
             * Environment
             * @description 运行环境：local | staging | production
             */
            environment: string;
            /**
             * Service
             * @description 服务标识
             */
            service: string;
            /**
             * Status
             * @description 进程存活即返回 ok
             * @constant
             */
            status: "ok";
            /**
             * Trace Id
             * @description 贯穿前后端的请求 ID
             */
            trace_id: string;
            /**
             * Uptime Seconds
             * @description 进程已运行秒数
             */
            uptime_seconds: number;
            /**
             * Version
             * @description 后端版本号
             */
            version: string;
        };
        /**
         * ObservabilityStatusResponse
         * @description 观测配置现状。用来回答「trace 为什么没出现」这类问题。
         * @example {
         *       "langfuse_configured": true,
         *       "langfuse_host": "http://localhost:3000",
         *       "langfuse_reachable": true,
         *       "llm_is_stub": true,
         *       "llm_model": "deepseek-chat",
         *       "llm_provider": "stub"
         *     }
         */
        ObservabilityStatusResponse: {
            /**
             * Langfuse Configured
             * @description 是否配齐了 public / secret key
             */
            langfuse_configured: boolean;
            /**
             * Langfuse Host
             * @description Langfuse 实例地址
             */
            langfuse_host: string;
            /**
             * Langfuse Reachable
             * @description auth_check 结果；未配置时为 null（而不是 false，二者含义不同）
             */
            langfuse_reachable?: boolean | null;
            /**
             * Llm Is Stub
             * @description true 表示不会发起真实网络调用
             */
            llm_is_stub: boolean;
            /**
             * Llm Model
             * @description 当前使用的模型名
             */
            llm_model: string;
            /**
             * Llm Provider
             * @description stub | openai-compatible
             */
            llm_provider: string;
        };
        /**
         * ServiceMetaEntry
         * @description `service_meta` 表的一行。
         */
        ServiceMetaEntry: {
            /** Key */
            key: string;
            /** Updated At */
            updated_at?: string | null;
            /** Value */
            value: string;
        };
        /**
         * SmokeRequest
         * @description 一次观测自检的入参。
         * @example {
         *       "prompt": "用一句话说明「岗位适配版简历」是什么意思。"
         *     }
         */
        SmokeRequest: {
            /**
             * Prompt
             * @default 用一句话说明「岗位适配版简历」是什么意思。
             */
            prompt: string;
            /**
             * System
             * @description 可选的 system 提示
             */
            system?: string | null;
        };
        /**
         * SmokeResponse
         * @description 一次被观测的 LLM 调用结果。
         *
         *     `trace_id` 是**规范化之后**给 Langfuse 用的 ID；`request_trace_id` 是前端下发的原始
         *     `X-Request-Id`。两者通常互为「去横线」关系，一并返回是为了便于人工核对。
         */
        SmokeResponse: {
            /**
             * Error
             * @description 失败原因
             */
            error?: string | null;
            /** Input Tokens */
            input_tokens?: number | null;
            /** Is Stub */
            is_stub: boolean;
            /** Langfuse Enabled */
            langfuse_enabled: boolean;
            /**
             * Langfuse Trace Url
             * @description 未启用或无 URL 时为 null
             */
            langfuse_trace_url?: string | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Model */
            model: string;
            /**
             * Ok
             * @description 调用是否成功；失败时 trace 里同样留有记录
             */
            ok: boolean;
            /**
             * Output
             * @description 失败时为 null
             */
            output?: string | null;
            /** Output Tokens */
            output_tokens?: number | null;
            /** Provider */
            provider: string;
            /** Request Trace Id */
            request_trace_id: string;
            /** Trace Id */
            trace_id: string;
        };
        /**
         * SystemInfoResponse
         * @description 穿透到数据库的系统信息。
         *
         *     M0-7 的验收就落在这个接口上：前端能把它渲染出来，
         *     就说明 UI → FastAPI → Postgres 这一条链路是通的。
         */
        SystemInfoResponse: {
            database: components["schemas"]["DatabaseStatus"];
            /** Environment */
            environment: string;
            /**
             * Meta
             * @description 来自 service_meta 表；数据库不可用时为空数组
             */
            meta: components["schemas"]["ServiceMetaEntry"][];
            /**
             * Milestone
             * @description 当前里程碑，用于自检页对照进度
             */
            milestone: string;
            /** Service */
            service: string;
            /** Trace Id */
            trace_id: string;
            /** Version */
            version: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    observability_smoke_api_v1_observability_smoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SmokeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SmokeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    observability_status_api_v1_observability_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservabilityStatusResponse"];
                };
            };
        };
    };
    system_info_api_v1_system_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemInfoResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
