/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/experiences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 列出经历条目
         * @description 返回当前用户的全部经历，**按分类分组、组内按经历时间倒序**（进行中的排在最前）。前端按这个顺序直接分组展示即可，不必再排一次。
         */
        get: operations["list_experiences_api_v1_experiences_get"];
        put?: never;
        /**
         * 新增一条经历
         * @description 素材库的录入入口（M2-4 的录入表单走这里）。
         */
        post: operations["create_experience_api_v1_experiences_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/experiences/{experience_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取一条经历 */
        get: operations["get_experience_api_v1_experiences__experience_id__get"];
        /**
         * 编辑一条经历（全量替换）
         * @description **PUT 语义：全量替换**，不是 PATCH。未提交的字段会按默认值处理（例如不传 `skill_tags` 等于清空标签），而不是保留旧值。
         *
         *     编辑表单提交的就是整条记录，全量语义下「必填字段缺失」由 Pydantic 直接拦成 422，省掉了 PATCH 里「字段没传」与「显式置空」的歧义。
         *
         *     `user_id` 与时间戳不可改；`updated_at` 由数据库触发器维护。
         */
        put: operations["update_experience_api_v1_experiences__experience_id__put"];
        post?: never;
        /** 删除一条经历 */
        delete: operations["delete_experience_api_v1_experiences__experience_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 健康检查
         * @description 进程级探活。**不访问数据库**，因此数据库挂掉时本接口仍返回 200。
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jd": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jds */
        get: operations["list_jds_api_v1_jd_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jd/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 解析 JD 文本为结构化岗位画像
         * @description 一次 LLM 调用把 JD 原文拆成必备技能 / 加分项 / 业务域 / 关键词 / 隐性偏好。
         *
         *     输出经 Pydantic 校验；**校验失败会自动带错误反馈重试**，重试次数体现在 `warnings` 里。
         */
        post: operations["parse_jd_api_v1_jd_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jd/parse-image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 视觉模型直读 JD 截图 */
        post: operations["parse_image_api_v1_jd_parse_image_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jd/{jd_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Jd */
        get: operations["get_jd_api_v1_jd__jd_id__get"];
        /** 修改 JD 标题和公司；原文与画像作为解析快照保留 */
        put: operations["update_jd_api_v1_jd__jd_id__put"];
        post?: never;
        /** Delete Jd */
        delete: operations["delete_jd_api_v1_jd__jd_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jd/{jd_id}/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Match Jd */
        post: operations["match_jd_api_v1_jd__jd_id__match_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/observability/smoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 观测自检：一次被完整 trace 的 LLM 调用
         * @description 发起一次 LLM 调用并按 trace → generation 两级结构上报 Langfuse。
         *
         *     **失败也算通过**：调用异常时 trace 照常落库，只是 observation 标记为 ERROR —— 观测的价值恰恰在于失败可查。
         */
        post: operations["observability_smoke_api_v1_observability_smoke_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/observability/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 观测配置现状
         * @description 回答「trace 为什么没出现」：key 是否配齐、实例是否可达、LLM 是不是 stub。
         */
        get: operations["observability_status_api_v1_observability_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/observability/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 生成成本与延迟汇总 */
        get: operations["observability_usage_api_v1_observability_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Resumes */
        get: operations["list_resumes_api_v1_resumes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/batch-generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Batch Generate */
        post: operations["batch_generate_api_v1_resumes_batch_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Batch Export */
        post: operations["batch_export_api_v1_resumes_export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 按 JD 生成一份简历
         * @description LangGraph 并行改写、事实校验、失败隔离与幂等落库。
         */
        post: operations["generate_resume_api_v1_resumes_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取生成任务 */
        get: operations["get_generation_run_api_v1_resumes_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/runs/{run_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 恢复中断的生成任务 */
        post: operations["resume_generation_run_api_v1_resumes_runs__run_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/runs/{run_id}/retry/{index}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 重试失败条目 */
        post: operations["retry_generation_item_api_v1_resumes_runs__run_id__retry__index__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Templates */
        get: operations["list_templates_api_v1_resumes_templates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/{resume_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取一份简历 */
        get: operations["get_resume_api_v1_resumes__resume_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/{resume_id}/ai-edits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Propose Edit */
        post: operations["propose_edit_api_v1_resumes__resume_id__ai_edits_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/{resume_id}/ai-edits/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Edit */
        get: operations["read_edit_api_v1_resumes__resume_id__ai_edits__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/{resume_id}/ai-edits/{run_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide Edit */
        post: operations["decide_edit_api_v1_resumes__resume_id__ai_edits__run_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/{resume_id}/editor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Editor */
        get: operations["get_editor_api_v1_resumes__resume_id__editor_get"];
        /** Save Editor */
        put: operations["save_editor_api_v1_resumes__resume_id__editor_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/{resume_id}/html": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 渲染简历 HTML（预览用）
         * @description 返回完整 HTML 文档，样式已内联。前端用 iframe 直接指向本地址即为所见即所得预览；服务端导出 PDF 时用的也是这份内容。
         */
        get: operations["get_resume_html_api_v1_resumes__resume_id__html_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/{resume_id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 导出简历 PDF
         * @description 用无头 Chromium 打印 `/{id}/html` 的同一份内容，默认 A4。
         *
         *     `download=1` 时以附件形式下载，否则浏览器内联预览。
         *     响应头 `X-Resume-Pages` 给出页数，便于自动化校验分页。
         */
        get: operations["export_resume_pdf_api_v1_resumes__resume_id__pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/{resume_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Draft */
        post: operations["preview_draft_api_v1_resumes__resume_id__preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/{resume_id}/revisions/{revision_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Revision */
        post: operations["restore_revision_api_v1_resumes__resume_id__revisions__revision_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/{resume_id}/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 评分并定向改进简历 */
        post: operations["score_resume_api_v1_resumes__resume_id__score_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resumes/{resume_id}/scores/{score_run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取评分历史与最佳版本 */
        get: operations["get_score_run_api_v1_resumes__resume_id__scores__score_run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 系统信息
         * @description 穿透到 Postgres 的读库校验。数据库不可用时降级返回，接口本身不报错。
         */
        get: operations["system_info_api_v1_system_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 健康检查
         * @description 进程级探活。**不访问数据库**，因此数据库挂掉时本接口仍返回 200。
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AiDecisionRequest */
        AiDecisionRequest: {
            /** Accept */
            accept: boolean;
        };
        /** AiEditRequest */
        AiEditRequest: {
            /** Entry Index */
            entry_index: number;
            /** Expected Revision */
            expected_revision: number;
            /** Instruction */
            instruction: string;
            /** Section Index */
            section_index: number;
        };
        /** AiEditResponse */
        AiEditResponse: {
            /** Base Revision */
            base_revision: number;
            editor?: components["schemas"]["EditorResponse"] | null;
            /** Entry Index */
            entry_index: number;
            /** Instruction */
            instruction: string;
            /** Is Stub */
            is_stub: boolean;
            /** Original Bullets */
            original_bullets: {
                [key: string]: unknown;
            }[];
            /** Proposed Bullets */
            proposed_bullets: {
                [key: string]: unknown;
            }[];
            /**
             * Resume Id
             * Format: uuid
             */
            resume_id: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Section Index */
            section_index: number;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "applied" | "rejected";
            /** Warnings */
            warnings: string[];
        };
        /** BatchExportRequest */
        BatchExportRequest: {
            /** Resume Ids */
            resume_ids: string[];
            /**
             * Template
             * @default classic
             */
            template: string;
        };
        /** BatchGenerateItem */
        BatchGenerateItem: {
            /** Error */
            error?: string | null;
            /**
             * Jd Id
             * Format: uuid
             */
            jd_id: string;
            /** Langfuse Trace Url */
            langfuse_trace_url?: string | null;
            /** Prompt Version */
            prompt_version?: string | null;
            resume?: components["schemas"]["ResumeRead"] | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "completed" | "partial" | "failed";
            /** Trace Id */
            trace_id?: string | null;
            usage?: components["schemas"]["GenerationUsage"];
            /** Warnings */
            warnings?: string[];
        };
        /** BatchGenerateRequest */
        BatchGenerateRequest: {
            /**
             * Batch Id
             * Format: uuid
             */
            batch_id?: string;
            /** Experience Ids */
            experience_ids?: string[];
            /** Jd Ids */
            jd_ids: string[];
        };
        /** BatchGenerateResponse */
        BatchGenerateResponse: {
            /**
             * Batch Id
             * Format: uuid
             */
            batch_id: string;
            /** Items */
            items: components["schemas"]["BatchGenerateItem"][];
        };
        /**
         * DatabaseStatus
         * @description 数据库探活结果。连不上不算接口失败，只降级。
         */
        DatabaseStatus: {
            /** Connected */
            connected: boolean;
            /**
             * Error
             * @description 连接失败原因，成功时为 null
             */
            error?: string | null;
            /**
             * Latency Ms
             * @description 探活往返耗时
             */
            latency_ms?: number | null;
            /**
             * Server Version
             * @description Postgres 版本
             */
            server_version?: string | null;
        };
        /** EditorResponse */
        EditorResponse: {
            /** History */
            history: components["schemas"]["ResumeRevision"][];
            resume: components["schemas"]["ResumeRead"];
            /** Revision */
            revision: number;
        };
        /**
         * ExperienceCreate
         * @description 新增经历的入参。
         *
         *     刻意**不含 user_id**：本项目是本地单机工具，用户由服务端按配置注入，
         *     不能让客户端指定（否则就是一个越权写入的洞）。
         */
        ExperienceCreate: {
            /**
             * End Date
             * @description 结束时间；进行中留空
             */
            end_date?: string | null;
            /**
             * Highlights
             * @description **定性**要点。改写只允许引用，不允许模型凭空生成
             */
            highlights?: string[];
            /**
             * Kind
             * @description 经历类型：项目 / 实习 / 校园
             * @enum {string}
             */
            kind: "project" | "internship" | "campus";
            /**
             * Metrics
             * @description **量化**结果。与 highlights 分开存放，便于自动校验「数字不可编造」（M4-7）
             */
            metrics?: components["schemas"]["ExperienceMetric"][];
            /**
             * Org
             * @description 组织、公司或项目名
             */
            org: string;
            /**
             * Raw Description
             * @description 原始描述。**事实基线** —— 后续改写的内容必须可回溯到这里
             */
            raw_description: string;
            /**
             * Role
             * @description 角色或职位
             */
            role: string;
            /**
             * Skill Tags
             * @description 技能标签
             */
            skill_tags?: string[];
            /**
             * Sort Order
             * @description 同一分类内的展示顺序。**M2 起 UI 不再维护**：列表按经历时间倒序，本字段降级为同时间条目的稳定排序兜底
             * @default 0
             */
            sort_order: number;
            /**
             * Start Date
             * @description 开始时间
             */
            start_date?: string | null;
            /**
             * Variants
             * @description 按岗位方向保存的多版本表述；同一条目同方向只允许一份
             */
            variants?: components["schemas"]["ExperienceVariant"][];
        };
        /** ExperienceListResponse */
        ExperienceListResponse: {
            /**
             * Items
             * @description 当前用户的经历条目，按分类分组、组内按经历时间倒序
             */
            items: components["schemas"]["ExperienceRead"][];
            /**
             * Total
             * @description 条目总数
             */
            total: number;
        };
        /** ExperienceMatch */
        ExperienceMatch: {
            /**
             * Experience Id
             * Format: uuid
             */
            experience_id: string;
            /** Matches */
            matches: components["schemas"]["RequirementMatch"][];
            /** Org */
            org: string;
            /** Role */
            role: string;
            /** Score */
            score: number;
        };
        /**
         * ExperienceMetric
         * @description 一条**量化结果**：这段经历里可测量的产出。
         *
         *     量化的是「成果」，不是过程、也不是技能。三要素缺一不可：
         *
         *         name    = 指标名，如「接口 P99 延迟」
         *         value   = 数值原文，如「800ms → 120ms」
         *         context = 口径，如「压测 5000 QPS 下」
         *
         *     `value` 刻意保持**字符串**而不是解析成数字 + 单位：
         *     简历里的量化写法千奇百怪（`24 → 82 条`、`3000+`、`下降 40%`），
         *     强行结构化只会让用户在录入时跟表单较劲。保持原样同样能满足
         *     「改写可回溯」——校验时做的是**子串匹配**，不需要理解数值语义。
         */
        ExperienceMetric: {
            /**
             * Context
             * @description 口径：怎么算的 / 什么范围，如「压测 5000 QPS 下」
             */
            context?: string | null;
            /**
             * Name
             * @description 指标名，如「接口 P99 延迟」
             */
            name: string;
            /**
             * Value
             * @description 数值原文，如「800ms → 120ms」
             */
            value: string;
        };
        /**
         * ExperienceRead
         * @description 读出的经历条目。
         * @example {
         *       "created_at": "2026-10-09T10:00:00Z",
         *       "highlights": [
         *         "接入 Langfuse 观测，每次 LLM 调用可按 trace_id 回放"
         *       ],
         *       "id": "00000000-0000-4000-8000-000000000101",
         *       "kind": "project",
         *       "metrics": [
         *         {
         *           "context": "后端 ruff + pytest 全绿",
         *           "name": "单元测试",
         *           "value": "24 → 82 条"
         *         }
         *       ],
         *       "org": "简历优化器",
         *       "raw_description": "独立设计与实现一个批量生成岗位适配版简历的 Web 工具……",
         *       "role": "独立开发",
         *       "skill_tags": [
         *         "Python",
         *         "FastAPI",
         *         "LangGraph"
         *       ],
         *       "sort_order": 0,
         *       "start_date": "2026-09-01",
         *       "updated_at": "2026-10-09T10:00:00Z",
         *       "user_id": "00000000-0000-4000-8000-000000000001",
         *       "variants": [
         *         {
         *           "direction": "后端开发",
         *           "note": "投后端岗时强调编排与工程化",
         *           "text": "用 FastAPI 承载全部业务逻辑，用 LangGraph 编排多步流程……"
         *         }
         *       ]
         *     }
         */
        ExperienceRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * End Date
             * @description 结束时间；进行中留空
             */
            end_date?: string | null;
            /**
             * Highlights
             * @description **定性**要点。改写只允许引用，不允许模型凭空生成
             */
            highlights?: string[];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Kind
             * @description 经历类型：项目 / 实习 / 校园
             * @enum {string}
             */
            kind: "project" | "internship" | "campus";
            /**
             * Metrics
             * @description **量化**结果。与 highlights 分开存放，便于自动校验「数字不可编造」（M4-7）
             */
            metrics?: components["schemas"]["ExperienceMetric"][];
            /**
             * Org
             * @description 组织、公司或项目名
             */
            org: string;
            /**
             * Raw Description
             * @description 原始描述。**事实基线** —— 后续改写的内容必须可回溯到这里
             */
            raw_description: string;
            /**
             * Role
             * @description 角色或职位
             */
            role: string;
            /**
             * Skill Tags
             * @description 技能标签
             */
            skill_tags?: string[];
            /**
             * Sort Order
             * @description 同一分类内的展示顺序。**M2 起 UI 不再维护**：列表按经历时间倒序，本字段降级为同时间条目的稳定排序兜底
             * @default 0
             */
            sort_order: number;
            /**
             * Start Date
             * @description 开始时间
             */
            start_date?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Variants
             * @description 按岗位方向保存的多版本表述；同一条目同方向只允许一份
             */
            variants?: components["schemas"]["ExperienceVariant"][];
        };
        /**
         * ExperienceUpdate
         * @description 编辑经历的入参 —— **PUT 全量替换**语义（M2-3）。
         *
         *     为什么是 PUT 而不是 PATCH：编辑表单提交的就是整条记录，
         *     全量语义下「必填字段缺失」直接被 Pydantic 拦成 422，不需要在服务层
         *     区分「字段没传」和「显式置空」这两种 PATCH 特有的歧义。
         *     与「Pydantic model 是接口类型唯一定义源」这条硬约定也最契合。
         *
         *     同样不含 `id` / `user_id` / 时间戳：这些不是用户能改的东西。
         */
        ExperienceUpdate: {
            /**
             * End Date
             * @description 结束时间；进行中留空
             */
            end_date?: string | null;
            /**
             * Highlights
             * @description **定性**要点。改写只允许引用，不允许模型凭空生成
             */
            highlights?: string[];
            /**
             * Kind
             * @description 经历类型：项目 / 实习 / 校园
             * @enum {string}
             */
            kind: "project" | "internship" | "campus";
            /**
             * Metrics
             * @description **量化**结果。与 highlights 分开存放，便于自动校验「数字不可编造」（M4-7）
             */
            metrics?: components["schemas"]["ExperienceMetric"][];
            /**
             * Org
             * @description 组织、公司或项目名
             */
            org: string;
            /**
             * Raw Description
             * @description 原始描述。**事实基线** —— 后续改写的内容必须可回溯到这里
             */
            raw_description: string;
            /**
             * Role
             * @description 角色或职位
             */
            role: string;
            /**
             * Skill Tags
             * @description 技能标签
             */
            skill_tags?: string[];
            /**
             * Sort Order
             * @description 同一分类内的展示顺序。**M2 起 UI 不再维护**：列表按经历时间倒序，本字段降级为同时间条目的稳定排序兜底
             * @default 0
             */
            sort_order: number;
            /**
             * Start Date
             * @description 开始时间
             */
            start_date?: string | null;
            /**
             * Variants
             * @description 按岗位方向保存的多版本表述；同一条目同方向只允许一份
             */
            variants?: components["schemas"]["ExperienceVariant"][];
        };
        /**
         * ExperienceVariant
         * @description 同一条经历在**某个岗位方向**下的表述版本（M2-6）。
         *
         *     典型用法：同一段「简历优化器」经历，投后端岗时强调 FastAPI / LangGraph 编排，
         *     投 AI 应用岗时强调 prompt 设计与评测。两份表述都真实，只是侧重不同。
         *
         *     变体是**派生内容**，事实基线仍是 `raw_description`。M2 阶段由用户手工维护，
         *     M4 起可由改写流程自动产出并回填。
         */
        ExperienceVariant: {
            /**
             * Direction
             * @description 岗位方向，如「后端开发」「AI 应用」
             */
            direction: string;
            /**
             * Note
             * @description 备注，如来源 JD / 使用建议
             */
            note?: string | null;
            /**
             * Text
             * @description 该方向下的表述
             */
            text: string;
        };
        /**
         * GenerateRequest
         * @description 一次「JD → 简历」生成的入参。
         */
        GenerateRequest: {
            /**
             * Experience Ids
             * @description 要用哪些经历。留空表示用当前用户的全部经历（走 M1-2 的素材库）
             */
            experience_ids?: string[];
            /**
             * Jd Id
             * @description 使用已保存的 JD，复用解析画像
             */
            jd_id?: string | null;
            /**
             * Jd Text
             * @description JD 原文，与 jd_id 二选一
             */
            jd_text?: string | null;
            /**
             * Persist
             * @description 是否落库；false 时只生成不保存
             * @default true
             */
            persist: boolean;
            /**
             * Run Id
             * @description 可由客户端指定，用于幂等生成和恢复
             */
            run_id?: string | null;
            /**
             * Title
             * @description 简历标题；留空则由岗位名推导
             */
            title?: string | null;
        };
        /**
         * GenerateResponse
         * @description 一次生成的结果。
         */
        GenerateResponse: {
            checkpoint: components["schemas"]["GenerationCheckpointRead"];
            /** Failures */
            failures: components["schemas"]["GenerationFailure"][];
            /** Is Stub */
            is_stub: boolean;
            /** Items */
            items: components["schemas"]["GenerationItem"][];
            /** Langfuse Trace Url */
            langfuse_trace_url?: string | null;
            /** Model */
            model: string;
            /**
             * Pdf Path
             * @description PDF 下载地址；persist=false 时为 null
             */
            pdf_path?: string | null;
            /**
             * Preview Path
             * @description 服务端渲染的 HTML 预览地址；persist=false 时为 null
             */
            preview_path?: string | null;
            /** @description 本次使用的岗位画像，便于前端展示「为什么这样改写」 */
            profile: components["schemas"]["JobProfile"];
            /** Prompt Version */
            prompt_version?: string | null;
            /** Provider */
            provider: string;
            resume: components["schemas"]["ResumeRead"];
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Trace Id */
            trace_id: string;
            /** @description 本次生成的 token、延迟与调用明细 */
            usage?: components["schemas"]["GenerationUsage"];
            /**
             * Warnings
             * @description 生成过程中的降级提示（stub、截断、JSON 重试等）
             */
            warnings: string[];
        };
        /** GenerationCheckpointRead */
        GenerationCheckpointRead: {
            /**
             * Backend
             * @enum {string}
             */
            backend: "postgres" | "memory";
            /** Resumable */
            resumable: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "completed" | "partial" | "failed";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** GenerationFailure */
        GenerationFailure: {
            /** Details */
            details?: string[];
            /** Error */
            error: string;
            /**
             * Experience Id
             * Format: uuid
             */
            experience_id: string;
            /** Index */
            index: number;
            /**
             * Retryable
             * @default true
             */
            retryable: boolean;
        };
        /** GenerationItem */
        GenerationItem: {
            entry?: components["schemas"]["ResumeEntry"] | null;
            /**
             * Experience Id
             * Format: uuid
             */
            experience_id: string;
            /** Index */
            index: number;
            /** Org */
            org: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "succeeded" | "failed";
        };
        /** GenerationUsage */
        GenerationUsage: {
            /** Calls */
            calls?: components["schemas"]["UsageCall"][];
            /** Cost Usd */
            cost_usd?: number | null;
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Is Stub
             * @default false
             */
            is_stub: boolean;
            /**
             * Latency Ms
             * @default 0
             */
            latency_ms: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
            /**
             * Total Tokens
             * @default 0
             */
            total_tokens: number;
            /**
             * Unknown Usage Calls
             * @default 0
             */
            unknown_usage_calls: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description 进程级健康检查结果。不依赖数据库，永远能返回。
         * @example {
         *       "checked_at": "2026-10-08T12:00:00Z",
         *       "environment": "local",
         *       "service": "resume-optimizer-api",
         *       "status": "ok",
         *       "trace_id": "8f1c0b2e6a4d4a1f9c3e7b5d2a0f6c11",
         *       "uptime_seconds": 12.5,
         *       "version": "0.1.0"
         *     }
         */
        HealthResponse: {
            /**
             * Checked At
             * Format: date-time
             * @description 本次检查时间（UTC）
             */
            checked_at: string;
            /**
             * Environment
             * @description 运行环境：local | staging | production
             */
            environment: string;
            /**
             * Service
             * @description 服务标识
             */
            service: string;
            /**
             * Status
             * @description 进程存活即返回 ok
             * @constant
             */
            status: "ok";
            /**
             * Trace Id
             * @description 贯穿前后端的请求 ID
             */
            trace_id: string;
            /**
             * Uptime Seconds
             * @description 进程已运行秒数
             */
            uptime_seconds: number;
            /**
             * Version
             * @description 后端版本号
             */
            version: string;
        };
        /** JdImageParseRequest */
        JdImageParseRequest: {
            /** Company */
            company?: string | null;
            /**
             * Image Data Url
             * @description PNG/JPEG/WebP data URL，≤5 MiB
             */
            image_data_url: string;
            /**
             * Persist
             * @default true
             */
            persist: boolean;
            /** Title */
            title?: string | null;
        };
        /** JdImageParseResponse */
        JdImageParseResponse: {
            /**
             * Is Stub
             * @description true 表示未发起真实网络调用（stub provider）
             */
            is_stub: boolean;
            /**
             * Jd Id
             * @description 落库后的记录 ID；persist=false 时为 null（前端应避免依赖它）
             */
            jd_id?: string | null;
            /**
             * Model
             * @description 本次使用的模型名
             */
            model: string;
            profile: components["schemas"]["JobProfile"];
            /**
             * Provider
             * @description 本次使用的 LLM provider
             */
            provider: string;
            /** Raw Text */
            raw_text: string;
            /**
             * Trace Id
             * @description 贯穿前后端的请求 ID，可在 Langfuse 按它回放
             */
            trace_id: string;
            /**
             * Warnings
             * @description 解析过程中的降级提示，例如「JSON 首次解析失败，已重试」
             */
            warnings: string[];
        };
        /** JdListResponse */
        JdListResponse: {
            /** Items */
            items: components["schemas"]["JdRead"][];
            /** Total */
            total: number;
        };
        /** JdMetadataUpdate */
        JdMetadataUpdate: {
            /** Company */
            company?: string | null;
            /** Title */
            title?: string | null;
        };
        /** JdParseRequest */
        JdParseRequest: {
            /**
             * Company
             * @description 可选的公司名补充
             */
            company?: string | null;
            /**
             * Persist
             * @description 是否落库；false 时只解析不保存
             * @default true
             */
            persist: boolean;
            /**
             * Raw Text
             * @description JD 原文，直接粘贴即可
             */
            raw_text: string;
            /**
             * Title
             * @description 可选的岗位标题补充
             */
            title?: string | null;
        };
        /**
         * JdParseResponse
         * @description 一次 JD 解析的结果。
         */
        JdParseResponse: {
            /**
             * Is Stub
             * @description true 表示未发起真实网络调用（stub provider）
             */
            is_stub: boolean;
            /**
             * Jd Id
             * @description 落库后的记录 ID；persist=false 时为 null（前端应避免依赖它）
             */
            jd_id?: string | null;
            /**
             * Model
             * @description 本次使用的模型名
             */
            model: string;
            profile: components["schemas"]["JobProfile"];
            /**
             * Provider
             * @description 本次使用的 LLM provider
             */
            provider: string;
            /**
             * Trace Id
             * @description 贯穿前后端的请求 ID，可在 Langfuse 按它回放
             */
            trace_id: string;
            /**
             * Warnings
             * @description 解析过程中的降级提示，例如「JSON 首次解析失败，已重试」
             */
            warnings: string[];
        };
        /**
         * JdRead
         * @description 落库后的 JD 记录。
         */
        JdRead: {
            /** Company */
            company?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            parsed?: components["schemas"]["JobProfile"] | null;
            /** Parser Model */
            parser_model?: string | null;
            /** Raw Text */
            raw_text: string;
            /**
             * Source Type
             * @default text
             */
            source_type: string;
            /** Title */
            title?: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /**
         * JobProfile
         * @description 结构化岗位画像。
         *
         *     列表字段必填；模型漏字段由结构化输出重试修正。
         * @example {
         *       "business_domain": "AI 应用 / 效率工具",
         *       "company": "某互联网公司",
         *       "implicit_preferences": [
         *         "偏好有从 0 到 1 独立交付经验的候选人"
         *       ],
         *       "keywords": [
         *         "高并发",
         *         "agent 编排",
         *         "可观测性"
         *       ],
         *       "nice_to_have": [
         *         "LangGraph",
         *         "Docker"
         *       ],
         *       "required_skills": [
         *         "Python",
         *         "FastAPI",
         *         "PostgreSQL"
         *       ],
         *       "responsibilities": [
         *         "负责后端服务的设计与实现",
         *         "参与 agent 流程编排"
         *       ],
         *       "seniority": "校招",
         *       "title": "后端开发工程师（校招）"
         *     }
         */
        JobProfile: {
            /**
             * Business Domain
             * @description 业务域
             */
            business_domain?: string | null;
            /**
             * Company
             * @description 公司名
             */
            company?: string | null;
            /**
             * Implicit Preferences
             * @description 没明说但能读出来的偏好（例如「抗压」「独立交付」）
             */
            implicit_preferences: string[];
            /**
             * Keywords
             * @description JD 里的高频关键词，用于对齐措辞
             */
            keywords: string[];
            /**
             * Nice To Have
             * @description 加分项
             */
            nice_to_have: string[];
            /**
             * Required Skills
             * @description 必备技能（硬性要求），改写时优先覆盖
             */
            required_skills: string[];
            /**
             * Responsibilities
             * @description 岗位职责条目
             */
            responsibilities: string[];
            /**
             * Seniority
             * @description 级别：实习 / 校招 / 社招-初级 / 社招-资深
             */
            seniority?: string | null;
            /**
             * Title
             * @description 岗位名称
             */
            title?: string | null;
        };
        /** JobRequirement */
        JobRequirement: {
            /**
             * Category
             * @enum {string}
             */
            category: "required" | "preferred" | "responsibility" | "domain";
            /** Id */
            id: string;
            /** Text */
            text: string;
            /** Weight */
            weight: number;
        };
        /** MatchRequest */
        MatchRequest: {
            /**
             * Candidate Limit
             * @default 20
             */
            candidate_limit: number;
        };
        /** MatchResponse */
        MatchResponse: {
            /** Embedding Model */
            embedding_model: string;
            /** Is Stub */
            is_stub: boolean;
            /** Items */
            items: components["schemas"]["ExperienceMatch"][];
            /**
             * Jd Id
             * Format: uuid
             */
            jd_id: string;
            /** Requirements */
            requirements: components["schemas"]["JobRequirement"][];
            /** Trace Id */
            trace_id: string;
            /** Uncovered Requirement Ids */
            uncovered_requirement_ids: string[];
            /** Warnings */
            warnings: string[];
        };
        /**
         * ObservabilityStatusResponse
         * @description 观测配置现状。用来回答「trace 为什么没出现」这类问题。
         * @example {
         *       "langfuse_configured": true,
         *       "langfuse_host": "http://localhost:3000",
         *       "langfuse_reachable": true,
         *       "llm_is_stub": true,
         *       "llm_model": "deepseek-chat",
         *       "llm_provider": "stub"
         *     }
         */
        ObservabilityStatusResponse: {
            /**
             * Langfuse Configured
             * @description 是否配齐了 public / secret key
             */
            langfuse_configured: boolean;
            /**
             * Langfuse Host
             * @description Langfuse 实例地址
             */
            langfuse_host: string;
            /**
             * Langfuse Reachable
             * @description auth_check 结果；未配置时为 null（而不是 false，二者含义不同）
             */
            langfuse_reachable?: boolean | null;
            /**
             * Llm Is Stub
             * @description true 表示不会发起真实网络调用
             */
            llm_is_stub: boolean;
            /**
             * Llm Model
             * @description 当前使用的模型名
             */
            llm_model: string;
            /**
             * Llm Provider
             * @description stub | openai-compatible
             */
            llm_provider: string;
        };
        /** RequirementMatch */
        RequirementMatch: {
            /** Evidence */
            evidence: string[];
            /** Reason */
            reason: string;
            /** Requirement Id */
            requirement_id: string;
            /** Score */
            score: number;
            /** Semantic Similarity */
            semantic_similarity: number | null;
            /** Shortlisted */
            shortlisted: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "covered" | "related" | "missing";
        };
        /** RestoreRevisionRequest */
        RestoreRevisionRequest: {
            /** Expected Revision */
            expected_revision: number;
        };
        /**
         * ResumeBullet
         * @description 简历里的一条要点。
         */
        ResumeBullet: {
            /** Evidence */
            evidence: string[];
            /** Text */
            text: string;
        };
        /** ResumeDraft */
        ResumeDraft: {
            header: components["schemas"]["ResumeHeader"];
            /** Sections */
            sections: components["schemas"]["ResumeSection"][];
            /** Title */
            title: string;
        };
        /**
         * ResumeEntry
         * @description 简历里的一段经历。
         *
         *     `org` / `role` / `period` 全部**来自原始经历条目**，不由模型产出。
         */
        ResumeEntry: {
            /** Bullets */
            bullets: components["schemas"]["ResumeBullet"][];
            /**
             * Experience Id
             * @description 来源经历条目 ID
             */
            experience_id: string | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "project" | "internship" | "campus";
            /** Org */
            org: string;
            /**
             * Period
             * @description 形如 2026.09 – 至今；无时间信息时为 null
             */
            period: string | null;
            /** Role */
            role: string;
        };
        /**
         * ResumeHeader
         * @description 简历抬头。M1 从 profiles 表取；M2-7 起可编辑。
         */
        ResumeHeader: {
            /** Headline */
            headline?: string | null;
            /** Name */
            name: string;
        };
        /** ResumeListResponse */
        ResumeListResponse: {
            /** Items */
            items: components["schemas"]["ResumeRead"][];
        };
        /**
         * ResumeRead
         * @description 一份生成的简历快照。
         * @example {
         *       "created_at": "2026-10-09T10:00:00Z",
         *       "generator": "stub:deepseek-chat(stub)",
         *       "header": {
         *         "headline": "后端 / AI 应用开发",
         *         "name": "本地开发用户"
         *       },
         *       "id": "11111111-1111-4111-8111-111111111111",
         *       "sections": [],
         *       "status": "draft",
         *       "template": "classic",
         *       "title": "后端开发工程师（校招）",
         *       "updated_at": "2026-10-09T10:00:00Z",
         *       "user_id": "00000000-0000-4000-8000-000000000001"
         *     }
         */
        ResumeRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Generator
             * @description 产出该简历的 provider:model
             */
            generator?: string | null;
            /**
             * Generator Vendor
             * @description 生成时记录的厂商；旧数据可能为空
             */
            generator_vendor?: string | null;
            header: components["schemas"]["ResumeHeader"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Jd Id */
            jd_id?: string | null;
            /** Sections */
            sections: components["schemas"]["ResumeSection"][];
            /**
             * Status
             * @description draft | exported
             */
            status: string;
            /**
             * Template
             * @default classic
             */
            template: string;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** ResumeRevision */
        ResumeRevision: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            draft: components["schemas"]["ResumeDraft"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Reason */
            reason: string;
            /** Revision */
            revision: number;
        };
        /**
         * ResumeSection
         * @description 简历的一个分区，例如「项目经历」「实习经历」。
         */
        ResumeSection: {
            /** Entries */
            entries: components["schemas"]["ResumeEntry"][];
            /** Title */
            title: string;
        };
        /** SaveRevisionRequest */
        SaveRevisionRequest: {
            /** Expected Revision */
            expected_revision: number;
            header: components["schemas"]["ResumeHeader"];
            /** Sections */
            sections: components["schemas"]["ResumeSection"][];
            /** Title */
            title: string;
        };
        /**
         * ScoreDeduction
         * @description 一处可执行的扣分和改进建议。
         */
        ScoreDeduction: {
            /** Bullet Index */
            bullet_index?: number | null;
            /**
             * Dimension
             * @enum {string}
             */
            dimension: "relevance" | "coverage" | "evidence" | "clarity";
            /** Item Index */
            item_index: number;
            /** Points */
            points: number;
            /** Reason */
            reason: string;
            /** Suggestion */
            suggestion: string;
        };
        /**
         * ScoreDimension
         * @description 一个 rubric 维度的得分。
         */
        ScoreDimension: {
            /**
             * Key
             * @enum {string}
             */
            key: "relevance" | "coverage" | "evidence" | "clarity";
            /** Label */
            label: string;
            /** Rationale */
            rationale: string;
            /** Score */
            score: number;
            /** Weight */
            weight: number;
            /** Weighted Score */
            weighted_score: number;
        };
        /**
         * ScoreLoopResult
         * @description 评分循环停止后的最佳版本和完整历史。
         */
        ScoreLoopResult: {
            best: components["schemas"]["ScoreSnapshot"];
            /** Snapshots */
            snapshots: components["schemas"]["ScoreSnapshot"][];
            /**
             * Stop Reason
             * @enum {string}
             */
            stop_reason: "threshold" | "max_rounds" | "cost_limit" | "no_low_score_items";
        };
        /**
         * ScoreRequest
         * @description 对已生成简历评分并按低分条目执行有限改进。
         */
        ScoreRequest: {
            /**
             * Cost Limit
             * @description 最大模型调用预算单位，含重试预留；不是货币
             * @default 100
             */
            cost_limit: number;
            /**
             * Max Rounds
             * @default 2
             */
            max_rounds: number;
            /**
             * Persist
             * @default true
             */
            persist: boolean;
            /**
             * Threshold
             * @default 80
             */
            threshold: number;
        };
        /** ScoreResponse */
        ScoreResponse: {
            loop: components["schemas"]["ScoreLoopResult"];
            /** Pdf Path */
            pdf_path?: string | null;
            /** Preview Path */
            preview_path?: string | null;
            profile: components["schemas"]["JobProfile"];
            resume: components["schemas"]["ResumeRead"];
            /** Resume Id */
            resume_id: string;
            /** Score Run Id */
            score_run_id?: string | null;
        };
        /**
         * ScoreResult
         * @description 一轮评分的完整结果。
         */
        ScoreResult: {
            /**
             * Blind
             * @description 评分输入已移除轮次和生成者信息
             */
            blind: boolean;
            /** Deductions */
            deductions: components["schemas"]["ScoreDeduction"][];
            /** Dimensions */
            dimensions: components["schemas"]["ScoreDimension"][];
            /**
             * Factual Violations
             * @description 原始素材核验失败的经历下标；不能作为最佳版本保存或导出
             */
            factual_violations?: number[];
            /**
             * Is Stub
             * @default false
             */
            is_stub: boolean;
            /** Item Scores */
            item_scores?: {
                [key: string]: number;
            };
            /** Judge Model */
            judge_model: string;
            /**
             * Judge Provider
             * @description 评分者 provider；与生成者分开记录
             */
            judge_provider: string;
            /**
             * Low Score Items
             * @description 需要定向重写的经历下标
             */
            low_score_items: number[];
            /** Recommendations */
            recommendations: string[];
            /** Score */
            score: number;
            /**
             * Usage Tokens
             * @default 0
             */
            usage_tokens: number;
            /** Warnings */
            warnings?: string[];
        };
        /**
         * ScoreSnapshot
         * @description 循环中的不可变历史快照。
         */
        ScoreSnapshot: {
            /** Cost */
            cost: number;
            result: components["schemas"]["ScoreResult"];
            /** Round */
            round: number;
            /** Sections */
            sections: {
                [key: string]: unknown;
            }[];
        };
        /**
         * ServiceMetaEntry
         * @description `service_meta` 表的一行。
         */
        ServiceMetaEntry: {
            /** Key */
            key: string;
            /** Updated At */
            updated_at?: string | null;
            /** Value */
            value: string;
        };
        /**
         * SmokeRequest
         * @description 一次观测自检的入参。
         * @example {
         *       "prompt": "用一句话说明「岗位适配版简历」是什么意思。"
         *     }
         */
        SmokeRequest: {
            /**
             * Prompt
             * @default 用一句话说明「岗位适配版简历」是什么意思。
             */
            prompt: string;
            /**
             * System
             * @description 可选的 system 提示
             */
            system?: string | null;
        };
        /**
         * SmokeResponse
         * @description 一次被观测的 LLM 调用结果。
         *
         *     `trace_id` 是**规范化之后**给 Langfuse 用的 ID；`request_trace_id` 是前端下发的原始
         *     `X-Request-Id`。两者通常互为「去横线」关系，一并返回是为了便于人工核对。
         */
        SmokeResponse: {
            /**
             * Error
             * @description 失败原因
             */
            error?: string | null;
            /** Input Tokens */
            input_tokens?: number | null;
            /** Is Stub */
            is_stub: boolean;
            /** Langfuse Enabled */
            langfuse_enabled: boolean;
            /**
             * Langfuse Trace Url
             * @description 未启用或无 URL 时为 null
             */
            langfuse_trace_url?: string | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Model */
            model: string;
            /**
             * Ok
             * @description 调用是否成功；失败时 trace 里同样留有记录
             */
            ok: boolean;
            /**
             * Output
             * @description 失败时为 null
             */
            output?: string | null;
            /** Output Tokens */
            output_tokens?: number | null;
            /** Provider */
            provider: string;
            /** Request Trace Id */
            request_trace_id: string;
            /** Trace Id */
            trace_id: string;
        };
        /**
         * SystemInfoResponse
         * @description 穿透到数据库的系统信息。
         *
         *     M0-7 的验收就落在这个接口上：前端能把它渲染出来，
         *     就说明 UI → FastAPI → Postgres 这一条链路是通的。
         */
        SystemInfoResponse: {
            database: components["schemas"]["DatabaseStatus"];
            /** Environment */
            environment: string;
            /**
             * Meta
             * @description 来自 service_meta 表；数据库不可用时为空数组
             */
            meta: components["schemas"]["ServiceMetaEntry"][];
            /**
             * Milestone
             * @description 当前里程碑，用于自检页对照进度
             */
            milestone: string;
            /** Service */
            service: string;
            /** Trace Id */
            trace_id: string;
            /** Version */
            version: string;
        };
        /** TemplateListResponse */
        TemplateListResponse: {
            /** Items */
            items: components["schemas"]["TemplateRead"][];
        };
        /** TemplateRead */
        TemplateRead: {
            /** Description */
            description: string;
            /** Id */
            id: string;
            /**
             * Layout
             * @enum {string}
             */
            layout: "single-column" | "two-column";
            /** Name */
            name: string;
        };
        /** UsageCall */
        UsageCall: {
            /** Cost Usd */
            cost_usd?: number | null;
            /** Id */
            id?: string | null;
            /** Input Tokens */
            input_tokens?: number | null;
            /**
             * Is Stub
             * @default false
             */
            is_stub: boolean;
            /**
             * Latency Ms
             * @default 0
             */
            latency_ms: number;
            /** Model */
            model: string;
            /** Operation */
            operation: string;
            /** Output Tokens */
            output_tokens?: number | null;
            /** Prompt Hash */
            prompt_hash?: string | null;
            /** Prompt Version */
            prompt_version?: string | null;
            /** Provider */
            provider: string;
            /**
             * Status
             * @default succeeded
             */
            status: string;
            /**
             * Total Tokens
             * @default 0
             */
            total_tokens: number;
        };
        /** UsageRun */
        UsageRun: {
            /** Langfuse Trace Url */
            langfuse_trace_url?: string | null;
            /** Run Id */
            run_id: string;
            /** Status */
            status?: string | null;
            /** Trace Id */
            trace_id?: string | null;
            /** Updated At */
            updated_at?: string | null;
            usage?: components["schemas"]["GenerationUsage"];
        };
        /** UsageSummaryResponse */
        UsageSummaryResponse: {
            /** Cost Usd */
            cost_usd?: number | null;
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Latency Ms
             * @default 0
             */
            latency_ms: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
            /** Runs */
            runs?: components["schemas"]["UsageRun"][];
            /**
             * Total Tokens
             * @default 0
             */
            total_tokens: number;
            /**
             * Unknown Usage Calls
             * @default 0
             */
            unknown_usage_calls: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_experiences_api_v1_experiences_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperienceListResponse"];
                };
            };
        };
    };
    create_experience_api_v1_experiences_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperienceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperienceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_experience_api_v1_experiences__experience_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experience_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperienceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_experience_api_v1_experiences__experience_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experience_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperienceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperienceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_experience_api_v1_experiences__experience_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experience_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_jds_api_v1_jd_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JdListResponse"];
                };
            };
        };
    };
    parse_jd_api_v1_jd_parse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JdParseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JdParseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_image_api_v1_jd_parse_image_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JdImageParseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JdImageParseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_jd_api_v1_jd__jd_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jd_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JdRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_jd_api_v1_jd__jd_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jd_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JdMetadataUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JdRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_jd_api_v1_jd__jd_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jd_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    match_jd_api_v1_jd__jd_id__match_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jd_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    observability_smoke_api_v1_observability_smoke_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SmokeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SmokeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    observability_status_api_v1_observability_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObservabilityStatusResponse"];
                };
            };
        };
    };
    observability_usage_api_v1_observability_usage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageSummaryResponse"];
                };
            };
        };
    };
    list_resumes_api_v1_resumes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeListResponse"];
                };
            };
        };
    };
    batch_generate_api_v1_resumes_batch_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchGenerateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    batch_export_api_v1_resumes_export_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "application/zip": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_resume_api_v1_resumes_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_generation_run_api_v1_resumes_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_generation_run_api_v1_resumes_runs__run_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_generation_item_api_v1_resumes_runs__run_id__retry__index__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                index: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_templates_api_v1_resumes_templates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateListResponse"];
                };
            };
        };
    };
    get_resume_api_v1_resumes__resume_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    propose_edit_api_v1_resumes__resume_id__ai_edits_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiEditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiEditResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_edit_api_v1_resumes__resume_id__ai_edits__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiEditResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_edit_api_v1_resumes__resume_id__ai_edits__run_id__decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiEditResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_editor_api_v1_resumes__resume_id__editor_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_editor_api_v1_resumes__resume_id__editor_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveRevisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_resume_html_api_v1_resumes__resume_id__html_get: {
        parameters: {
            query?: {
                /** @description 覆盖模板；缺省用简历自身记录的模板 */
                template?: string | null;
            };
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_resume_pdf_api_v1_resumes__resume_id__pdf_get: {
        parameters: {
            query?: {
                /** @description true 时强制下载而非内联预览 */
                download?: boolean;
                /** @description 覆盖导出模板，不修改简历内容 */
                template?: string | null;
            };
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "application/pdf": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_draft_api_v1_resumes__resume_id__preview_post: {
        parameters: {
            query?: {
                /** @description 预览模板，不保存到编辑版本 */
                template?: string | null;
            };
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeDraft"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "application/pdf": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_revision_api_v1_resumes__resume_id__revisions__revision_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
                revision_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RestoreRevisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    score_resume_api_v1_resumes__resume_id__score_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScoreRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_score_run_api_v1_resumes__resume_id__scores__score_run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                resume_id: string;
                score_run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    system_info_api_v1_system_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemInfoResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
