/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 健康检查
         * @description 进程级探活。**不访问数据库**，因此数据库挂掉时本接口仍返回 200。
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 系统信息
         * @description 穿透到 Postgres 的读库校验。数据库不可用时降级返回，接口本身不报错。
         */
        get: operations["system_info_api_v1_system_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 健康检查
         * @description 进程级探活。**不访问数据库**，因此数据库挂掉时本接口仍返回 200。
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * DatabaseStatus
         * @description 数据库探活结果。连不上不算接口失败，只降级。
         */
        DatabaseStatus: {
            /** Connected */
            connected: boolean;
            /**
             * Error
             * @description 连接失败原因，成功时为 null
             */
            error?: string | null;
            /**
             * Latency Ms
             * @description 探活往返耗时
             */
            latency_ms?: number | null;
            /**
             * Server Version
             * @description Postgres 版本
             */
            server_version?: string | null;
        };
        /**
         * HealthResponse
         * @description 进程级健康检查结果。不依赖数据库，永远能返回。
         * @example {
         *       "checked_at": "2026-10-08T12:00:00Z",
         *       "environment": "local",
         *       "service": "resume-optimizer-api",
         *       "status": "ok",
         *       "trace_id": "8f1c0b2e6a4d4a1f9c3e7b5d2a0f6c11",
         *       "uptime_seconds": 12.5,
         *       "version": "0.1.0"
         *     }
         */
        HealthResponse: {
            /**
             * Checked At
             * Format: date-time
             * @description 本次检查时间（UTC）
             */
            checked_at: string;
            /**
             * Environment
             * @description 运行环境：local | staging | production
             */
            environment: string;
            /**
             * Service
             * @description 服务标识
             */
            service: string;
            /**
             * Status
             * @description 进程存活即返回 ok
             * @constant
             */
            status: "ok";
            /**
             * Trace Id
             * @description 贯穿前后端的请求 ID
             */
            trace_id: string;
            /**
             * Uptime Seconds
             * @description 进程已运行秒数
             */
            uptime_seconds: number;
            /**
             * Version
             * @description 后端版本号
             */
            version: string;
        };
        /**
         * ServiceMetaEntry
         * @description `service_meta` 表的一行。
         */
        ServiceMetaEntry: {
            /** Key */
            key: string;
            /** Updated At */
            updated_at?: string | null;
            /** Value */
            value: string;
        };
        /**
         * SystemInfoResponse
         * @description 穿透到数据库的系统信息。
         *
         *     M0-7 的验收就落在这个接口上：前端能把它渲染出来，
         *     就说明 UI → FastAPI → Postgres 这一条链路是通的。
         */
        SystemInfoResponse: {
            database: components["schemas"]["DatabaseStatus"];
            /** Environment */
            environment: string;
            /**
             * Meta
             * @description 来自 service_meta 表；数据库不可用时为空数组
             */
            meta: components["schemas"]["ServiceMetaEntry"][];
            /**
             * Milestone
             * @description 当前里程碑，用于自检页对照进度
             */
            milestone: string;
            /** Service */
            service: string;
            /** Trace Id */
            trace_id: string;
            /** Version */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    system_info_api_v1_system_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemInfoResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
